In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [12]:
print(a.shape)

(5,)


In [14]:
b=np.array([[1],[2],[3]])

In [22]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
a=np.full((3,2),5)

In [34]:
print(a)

[[5 5]
 [5 5]
 [5 5]]


In [45]:
b=np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
c=np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
d=np.eye(4)
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
RandomMatrix=np.random.random((2,3))


In [69]:
print(RandomMatrix)

[[0.12876679 0.89680855 0.46717874]
 [0.51118551 0.98599963 0.90354738]]


In [74]:
RandomMatrix[1,1:3]=[10,20]

In [75]:
RandomMatrix

array([[ 0.12876679,  0.89680855,  0.46717874],
       [ 0.51118551, 10.        , 20.        ]])

In [81]:
# Setting a particular row and column with particular number
z=np.zeros((3,3))
z[1,:]=3
z[:,2]=7
z

array([[0., 0., 7.],
       [3., 3., 7.],
       [0., 0., 7.]])

In [90]:
#Changing datatype
z=np.zeros((3,3), dtype=np.int64)
z[1,:]=3
z[:,2]=7
print(z)

[[0 0 7]
 [3 3 7]
 [0 0 7]]


In [106]:
# Mathematical Operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print(y,end='')

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

In [102]:
print(x+y)
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.sqrt(x))


[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [103]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [117]:
# Multiplication of Vectors => Scalars
a=np.array([1,2,3,5])
b=np.array([1,2,3,4])

In [110]:
print(np.dot(a,b))


30


In [111]:
print(np.cross(x,y))

[-4 -4]


In [112]:
print(x)

[[1 2]
 [3 4]]


In [122]:
print(x)

[[1 2]
 [3 4]]


In [124]:
print(np.sum(x,axis=1))

[3 7]


In [125]:
print(y)

[[5 6]
 [7 8]]


In [132]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [137]:
# Stacking of arrays
print(np.hstack((x,y)))

[[1 2 5 6]
 [3 4 7 8]]


In [154]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
b=b**2
print(a)
print(b)
print(np.stack((a,b),axis=1))

[1 2 3 4]
[ 1  4  9 16]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]


In [160]:
# Reshape
x=x.reshape(4,1)
x

array([[1],
       [2],
       [3],
       [4]])

In [162]:
# Automatically identifies the number of rows and columns
x.reshape(4,-1)

array([[1],
       [2],
       [3],
       [4]])

In [168]:
print(np.random.random((4,2)))

[[0.12899941 0.41536989]
 [0.96478557 0.39696729]
 [0.57035954 0.4087637 ]
 [0.13435313 0.58532572]]


In [194]:
# Random function modules
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [195]:
(np.random.shuffle(a))
a

array([3, 7, 2, 5, 6, 4, 0, 8, 1, 9])

In [197]:
print(a)

[3 7 2 5 6 4 0 8 1 9]


In [198]:
a=np.random.rand(2,3)

In [199]:
a

array([[0.46348304, 0.95553923, 0.54686002],
       [0.74472974, 0.63221208, 0.66883613]])

In [200]:
a=np.random.random((2,3))

In [201]:
a

array([[0.72423548, 0.50942174, 0.84357964],
       [0.23040846, 0.49318274, 0.487258  ]])

In [202]:
# Standard normal distribution
b=np.random.randn(2,3)

In [203]:
b

array([[-0.50462098, -0.51390109,  0.49919624],
       [-1.05905094,  0.46135762, -1.90807306]])

In [213]:
a=np.random.randint(5,10,3)
a

array([5, 6, 9])

In [219]:
# Using Seed to Store the previous random State
np.random.seed(1)
a=np.random.randint(10,99,6)
print(a)


[47 22 82 19 85 15]


In [224]:
# Using Mean, Median and Statistical Functions
a=np.array([[7,4,5,0],[1,8,2,9]])
a

array([[7, 4, 5, 0],
       [1, 8, 2, 9]])

In [226]:
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[1 4 2 0]
[0 1]


In [229]:
# Mean and average
print(np.mean(a,axis=0))

[4.  6.  3.5 4.5]


In [238]:
print(a)

[[7 4 5 0]
 [1 8 2 9]]


In [239]:
w=np.array([1,2,3,4])

print(np.average(a,weights=w, axis=1))

[3.  5.9]


In [253]:
# Standard deviation and variance
a=np.array([1,2,3,4])
size=np.size(a)
mean=np.mean(a)
print(mean)
print(np.sqrt(np.mean(abs(a-mean)**2)))
print(np.std(a))
print(np.var(a))

2.5
1.118033988749895
1.118033988749895
1.25
